"""adding_truncate_posts

Revision ID: 12ca4cba34c
Revises: b0d89871be
Create Date: 2015-03-12 09:01:20.829600

"""

# revision identifiers, used by Alembic.
revision = '12ca4cba34c'
down_revision = 'b0d89871be'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

from migrations.utils import drop_column_sqlite

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blog_truncate_posts', sa.Boolean(), nullable=True))
    op.execute(table('user', column('blog_truncate_posts')).update().values(
        {'blog_truncate_posts': op.inline_literal(False)})
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    drop_column_sqlite('user', 'blog_truncate_posts')
    ### end Alembic commands ###
