"""adding_syntax_highlighter_choice

Revision ID: 13234475ad5
Revises: 12ca4cba34c
Create Date: 2015-03-12 10:28:43.604768

"""

# revision identifiers, used by Alembic.
revision = '13234475ad5'
down_revision = '12ca4cba34c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

from migrations.utils import drop_column_sqlite

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blog_syntax_highlighter_css', sa.Enum('autumn.css', 'borland.css', 'bw.css', 'colorful.css', 'default.css', 'emacs.css', 'friendly.css', 'fruity.css', 'github.css', 'manni.css', 'monokai.css', 'murphy.css', 'native.css', 'pastie.css', 'perldoc.css', 'tango.css', 'trac.css', 'vim.css', 'vs.css', 'zenburn.css'), nullable=True))
    op.execute(table('user', column('blog_syntax_highlighter_css')).update().values(
        {'blog_syntax_highlighter_css': "monokai.css"})
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    drop_column_sqlite('user', 'blog_syntax_highlighter_css')
    ### end Alembic commands ###
