"""adding_paginate_and_post_slug

Revision ID: 3a35afe64d1
Revises: 2870937c5fa
Create Date: 2015-02-17 11:52:08.612681

"""

# revision identifiers, used by Alembic.
revision = '3a35afe64d1'
down_revision = '2870937c5fa'

from alembic import op
import sqlalchemy as sa

from migrations.utils import drop_column_sqlite

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title_slug', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('blog_paginate', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('blog_paginate_by', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    drop_column_sqlite('user', 'blog_paginate_by')
    drop_column_sqlite('user', 'blog_paginate')
    drop_column_sqlite('post', 'title_slug')
    ### end Alembic commands ###
