"""empty message

Revision ID: 9144c5cad
Revises: None
Create Date: 2015-02-05 09:53:36.355874

"""

# revision identifiers, used by Alembic.
revision = '9144c5cad'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
