"""adding_public_blog

Revision ID: b0d89871be
Revises: 3a35afe64d1
Create Date: 2015-02-18 11:36:39.504306

"""

# revision identifiers, used by Alembic.
revision = 'b0d89871be'
down_revision = '3a35afe64d1'

from alembic import op
import sqlalchemy as sa

from migrations.utils import drop_column_sqlite
from app.models import User

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blog_public', sa.Boolean(), nullable=True))
    for user in User.query.all():
        user.blog_public = True
        user.save()
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    drop_column_sqlite('user', 'blog_public')
    ### end Alembic commands ###
